[budf]
version = 1

[userscript]
name = "Sparkle"
id = "sparkle"
version = "v1.0.0"
match = [
    "*://snap.berkeley.edu/snap/snap.html",
    "*://snap.berkeley.edu/snap/dev/snap.html",
    "*://e016.github.io/split-mod/split.html",
    "*://codingisfun2831t.github.io/split-mod-prs/split.html",
    "*://alessandrito123.github.io/Snavanced/snap.html",
]
