name: Generate RoboTorvalds commentary
on:
  pull_request:
    branches:
      - main
jobs:
  robotorvalds:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          
      - run: printf "TORVALDS=$(grep . torvalds.txt | tail -n +2 | shuf -n 1)\n" >> "$GITHUB_ENV"

      - uses: mshick/add-pr-comment@v3
        with:
          message: 'To quote Linus Torvalds: \"${{ env.TORVALDS }}\"'
